// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ObrashcheniyaWeb.Data;

#nullable disable

namespace ObrashcheniyaWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616014844_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ObrashcheniyaWeb.Models.Appeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_Обращения");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CitizenId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Гражданина");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("date")
                        .HasColumnName("Дата_исполнения");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Описание");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Сотрудника");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Типа");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("Результат");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Статуса");

                    b.Property<DateTime>("SubmissionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("Дата_поступления")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RequestTypeId");

                    b.HasIndex("StatusId");

                    b.ToTable("Обращения", (string)null);
                });

            modelBuilder.Entity("ObrashcheniyaWeb.Models.Citizen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_Гражданина");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Адрес");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("Дата_рождения");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Имя");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Фамилия");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Отчество");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Телефон");

                    b.HasKey("Id");

                    b.ToTable("Граждане", (string)null);
                });

            modelBuilder.Entity("ObrashcheniyaWeb.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_Сотрудника");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ФИО");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Логин");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Пароль");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Должность");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("пользователь")
                        .HasColumnName("Роль");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Сотрудники", (string)null);
                });

            modelBuilder.Entity("ObrashcheniyaWeb.Models.RequestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_Типа");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Описание");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Название");

                    b.HasKey("Id");

                    b.ToTable("Типы_обращений", (string)null);
                });

            modelBuilder.Entity("ObrashcheniyaWeb.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_Статуса");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Название");

                    b.HasKey("Id");

                    b.ToTable("Статусы", (string)null);
                });

            modelBuilder.Entity("ObrashcheniyaWeb.Models.Appeal", b =>
                {
                    b.HasOne("ObrashcheniyaWeb.Models.Citizen", "Citizen")
                        .WithMany("Appeals")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ObrashcheniyaWeb.Models.Employee", "Employee")
                        .WithMany("Appeals")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ObrashcheniyaWeb.Models.RequestType", "RequestType")
                        .WithMany("Appeals")
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ObrashcheniyaWeb.Models.Status", "Status")
                        .WithMany("Appeals")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Citizen");

                    b.Navigation("Employee");

                    b.Navigation("RequestType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ObrashcheniyaWeb.Models.Citizen", b =>
                {
                    b.Navigation("Appeals");
                });

            modelBuilder.Entity("ObrashcheniyaWeb.Models.Employee", b =>
                {
                    b.Navigation("Appeals");
                });

            modelBuilder.Entity("ObrashcheniyaWeb.Models.RequestType", b =>
                {
                    b.Navigation("Appeals");
                });

            modelBuilder.Entity("ObrashcheniyaWeb.Models.Status", b =>
                {
                    b.Navigation("Appeals");
                });
#pragma warning restore 612, 618
        }
    }
}
